version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      version-minor-and-patch:
        applies-to: version-updates
        update-types:
          - "minor"
          - "patch"
      security-minor-and-patch:
        applies-to: security-updates
        update-types:
          - "minor"
          - "patch"


        
