version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    versioning-strategy: increase
    groups:
      version-major:
        applies-to: version-updates
        update-types:
          - "major"
      version-minor:
        applies-to: version-updates
        update-types:
          - "minor"
      version-patch:
        applies-to: version-updates
        update-types:
          - "patch"
      security-major:
        applies-to: security-updates
        update-types:
          - "major"
      security-minor:
        applies-to: security-updates
        update-types:
          - "minor"
      security-patch:
        applies-to: security-updates
        update-types:
          - "patch"

        
