name: Audit
on:
    workflow_dispatch:
    push:
        branches:
            main
    
jobs:
    audit:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
            
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: latest
                cache: npm
            
            - name: Audit frontend
              run: npm audit --json -w @joshnice/blog-frontend

            - name: Audit api
              run: npm audit --json -w @joshnice/blog-api