name: Back-end
on:
    workflow_dispatch:
    push:
        branches:
            main
        paths:
            backend/**
            .github/*
    
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                sparse-checkout: ./backend
            
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws-region: eu-west-2
            
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: latest
                cache: npm
            
            - name: List folders
              run: ls

            # - name: Install dependencies
            #   run: npm i -w @joshnice/blog-backend

            # - name: Build
            #   run: npm run build -w @joshnice/blog-backend

            # - name: Zip build and dependencies
            #   run: zip -r api-build ./backend/dist ./node_modules
            
            # - name: Sync S3 bucket 
            #   run: aws s3 cp api-build.zip s3://joshliamnice-api

